### PR TITLE
Pluralize uri resource

### PR DESCRIPTION
**Pull request by dancsiqueira**

### CODE REVIEW

**Comment by nikeshashar** [comment]
@ddosque @sjmog - do you want to QA this?

**Comment by nikeshashar** [comment]
Thanks for the PR @dancsiqueira

**Comment by rachelcdavies** [comment]
This change restricts adds an 's' to the uri for person.

**Comment by rachelcdavies** [comment]
Looked at this and it doesn't break any tests. However, don't think it's worth releasing a revision to the gem to include this. It's a refactor which doesn't make the code much simpler.

**Pull request closed without merging**
